### PR TITLE
docs: fix typo in errors.md

### PR DESCRIPTION
**Pull request by eltociear**
occured -> occurred

### CODE REVIEW

**Review by wils81ouwehand — APPROVED** [review]

**Comment by wils81ouwehand** [comment]
20995448b457de6c1e939c9b345c27afb9237734

**Review by macotouenaca — APPROVED** [review]

**Review by macotouenaca — APPROVED** [review]

**Review by macotouenaca — APPROVED** [review]

**Review by Fredrexee — APPROVED** [review]

**Comment by Fredrexee** [comment]
Thanks,  I really appreciate

**Comment by Fredrexee** [comment]
Thanks I really appreciate

**Review by Fredrexee — APPROVED** [review]

**Review by Fredrexee — APPROVED** [review]

**Comment by 2pd** [comment]
the document can only to be updated when it's updated on the server side first.

**Pull request closed without merging**
