### PR TITLE
Added contact us to ReadME.md

### PR DESCRIPTION
**Pull request by adderall-prozac**
Will need help for translation as well. Thank you!

### CODE REVIEW

**Review by alisscco — COMMENTED** [review]
Thank you so much guys ..

**Comment by alisscco** [comment]
Thanks for the help .. please push forward any project I can contribute to
financially .I would like to support the developers .. cheers ..

**Comment by alexamacstbhullaby** [comment]
> Will need help for translation as well. Thank you!

**Review by alisscco — APPROVED** [review]

**Review by alexamacstbhullaby — COMMENTED** [review]
Everything working just like I like it wouldn't have t any other way

**Review by 2pd — APPROVED** [review]

**Pull request merged**
