### PR TITLE
Updates to testnet

### PR DESCRIPTION
**Pull request by adderall-prozac**

### CODE REVIEW

**Comment by chris6090** [comment]
Kriseng83@gmail.com

**Comment by sytranvn** [comment]
@adderall-prozac 
It seems like `https://testnet.binance.vision/api/v3/account` endpoint does not send updated account balances after order filled.

**Comment by chris6090** [comment]
Kriseng83@gmail.com

**Comment by chris6090** [comment]
Christ Nwachukwu 
Kriseng83@gmail.com

**Comment by chris6090** [comment]
> @adderall-prozac 
> It seems like `https://testnet.binance.vision/api/v3/account` endpoint does not send updated account balances after order filled. 

Kriseng83@gmail.com

**Pull request merged**
