### PR TITLE
Mention the `limit` mechanism in `aggTrades`

### LINKED ISSUE #10: `aggTrades` works incorrectly
According to the docs:

> Trades that fill at the time, from the same taker order, with the same price will have the quantity aggregated.

The first part (`Trades that fill at the time`) is false. Here's an example:

1. https://api.binance.com/api/v3/aggTrades?symbol=NEBLBTC&limit=1000&startTime=1609609200000&endTime=1609609440000
2. https://api.binance.com/api/v3/aggTrades?symbol=NEBLBTC&limit=1000&startTime=1609609200000&endTime=1609612800000

Do note the start time in both cases is the same, only end time differs. So the first trade returned by both calls should be the same. It isn't. The first order time from no 1 is 16096`09203988` while from no 2 it is 16096`10589954`.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes  #10

### CODE REVIEW

**Comment by porn354** [comment]
TZ3VA4UQJ9IG3UWHPZ8M2CQR87WKXKAM1U

**Comment by porn354** [comment]
``0xbe0eb53f46cd790cd13851d5eff43d12404d33e8

**Comment by porn354** [comment]
0x00000000219ab540356cbb839cbe05303d7705fa

**Comment by stunnamaneee** [comment]
Thanks

**Comment by 2pd** [comment]
we are still reviewing this.

**Comment by IMFALHUSSAIN** [comment]
********

**Review by Rezduan83 — APPROVED** [review]

**Comment by Mehmetbatmaz** [comment]
Mehmetbatmazzzz

**Review by aboody8007 — APPROVED** [review]
pg

**Pull request closed without merging**
