### PR TITLE
All orders

### PR DESCRIPTION
**Pull request by adderall-prozac**
adding clarification to the allOrders endpoint

### CODE REVIEW

**Review by 2pd — APPROVED** [review]

**Comment by Boecboyko555** [comment]
Я не правильно что-то сделал?

**Comment by ROMANA0332** [comment]
{
  "result": [
    "btcusdt@aggTrade"
  ],
  "id": 3
}

**Comment by ROMANA0332** [comment]
{
  "method": "LIST_SUBSCRIPTIONS",
  "id": 3
}

**Comment by ROMANA0332** [comment]
{
  "result": null,
  "id": 312
}

**Comment by ROMANA0332** [comment]
{
  "method": "UNSUBSCRIBE",
  "params": [
    "btcusdt@depth"
  ],
  "id": 312
}

**Comment by ROMANA0332** [comment]
{
  "result": null,
  "id": 1
}

**Comment by ROMANA0332** [comment]
{
  "method": "SUBSCRIBE",
  "params": [
    "btcusdt@aggTrade",
    "btcusdt@depth"
  ],
  "id": 1
}

**Comment by ROMANA0332** [comment]
https://quickshare.samsungcloud.com/gvqNktNmvrYn

**Comment by ROMANA0332** [comment]
Want to trade like the experts without spending hours monitoring the markets? Copy Trading lets you automatically mirror the strategies of experienced traders in real time!
Whether you're a beginner looking to learn or a busy investor wanting to capitalize on expert insights, Copy Trading can be a game-changer.
Have you tried Copy Trading? Share your success stories, lessons learned, or top tips for choosing the right Lead Trader! Let's discuss how to maximize results and minimize risks.

**Pull request merged**
