### PR TITLE
Create lounging error

### PR DESCRIPTION
**Pull request by AungThuSoe24**

### CODE REVIEW

**Comment by AungThuSoe24** [comment]
Withdrawal

**Review by AungThuSoe24 — COMMENTED** [review]
Withdrawal

**Review by MMONSTER124 — COMMENTED** [review]
cfef152103268d318637f704d9fddf743923e714

**Review by AungThuSoe24 — COMMENTED** [review]
Request for Bitget proof of reversal

**Comment by chris6090** [comment]
> _ No description provided. _

Kriseng83@gmail.com

**Pull request closed without merging**
