### PR TITLE
add links to new connectors repo

### PR DESCRIPTION
**Pull request by chairz**

### CODE REVIEW

**Comment by Sahismail** [comment]
https://binance-docs.github.io/apidocs/spot/en/#all-book-tickers-stream

**Review by aisling11 — APPROVED** [review]

**Review by Alexalucky — APPROVED** [review]

**Review by Stig0812 — APPROVED** [review]

**Comment by Alexalucky** [comment]
Good

**Comment by Alexalucky** [comment]
Wow!

**Comment by Alexalucky** [comment]
[go]()

**Comment by bullibasti** [comment]
Am 19.12.2021 05:31 schrieb Alexalucky ***@***.***>:
Wow!

**Pull request merged**
