### PR TITLE
update cn document

### PR DESCRIPTION
**Pull request by 2pd**

### CODE REVIEW

**Comment by BachVanDuan** [comment]
Help.
Announcement today 6:30 am G7 time .has meeting on open source code.  Need
someone to secure this open source network for me as well as future use
organization.  You notify everyone with
BạchVănDuẩn

Vào 11:45, T.2, 12 Th12, 2022 Jeremy ***@***.***> đã viết:

**Comment by BachVanDuan** [comment]
Alo

**Comment by BachVanDuan** [comment]
Announcement today 6:30 am G7 time .has meeting on open source code.  Need someone to secure this open source network for me as well as future use organization.  You notify everyone with

**Comment by BachVanDuan** [comment]
He thong looks like someone edited it.  I want to ask why are the licenses floating around

**Review by Dickyvio44 — COMMENTED** [review]
A

**Review by octavio12345300 — COMMENTED** [review]
LISTO

**Pull request merged**
