### PR TITLE
My trades newcombinations

### PR DESCRIPTION
**Pull request by hstoresin**
CHANGELOG.md

### CODE REVIEW

**Review by WOAftp — COMMENTED** [review]
{
  "method": "SUBSCRIBE",
  "params": [
    "btcusdt@aggTrade",
    "btcusdt@depth"
  ],
  "id": 1
}

**Review by Boecboyko555 — COMMENTED** [review]
Блин, помогите разобраться где что..?

**Review by janl3577 — COMMENTED** [review]
Thanks

**Review by independentcontractor66666gma — COMMENTED** [review]
evanschriswell34@gmail.com

**Review by marymaie22 — COMMENTED** [review]
Code

**Comment by Chesney97** [comment]
Hey giys sorry on me last mesaage ive been under lot of stress alot has been going wrong on me and last thing i meeded was this to go wromg i have had a look over the changes made via thw link and tbh i was worried and wasnt happy when seen the master being merged i to a new thing i do hope master and my others are safe and wont be changed wirhouth my knowledge im not very good at this coding part but have a serious vast lnowledge and abilites right across the crypto etc systems i do appeaciate ur help and time and look forward to more work in thw futurw but plea see if poosi le kep me wel informed and up to date also how do u recieve moeny owed from the app or how do i get paid ive been at this 5 years and never made a cent

**Pull request closed without merging**
