### PR TITLE
fix the format to compatible mdx

### PR DESCRIPTION
**Pull request by beiciye**
1. To fix some tags not closed. 
2.  Fix the attribute value without quota

### CODE REVIEW

**Review by adderall-prozac — APPROVED** [review]

**Comment by hstoresin** [comment]
gh repo clone binance/binance-spot-api-docs

**Comment by R-S-M-A-N** [comment]
@beiciye  I just consulted your guide "trailing-stop-faq.md" but I can't find the solution to place a buy or sell order at a fixed price, (Example 10000 to 10000 and not 10001.99 or 9992.08).
I manage to do it on the site but not via the API, do you have a idea/solution?

**Comment by Boecboyko555** [comment]
Я не пойму вас, что от меня нужно сделать?

вс, 22 янв. 2023 г., 15:50 R-S-M-A-N ***@***.***>:

**Review by rahmanAkmfz — COMMENTED** [review]
No

**Pull request merged**
